### ISSUE TITLE
Esecuzione di uno script Python

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/Helloworld1#1]
Manda in esecuzione con

``` bash
$ python helloworld.py
```

**Comment by FabioZTessitore** [comment]
sei riuscito a mandare in esecuzione il programma di esempio?

**Comment by Raffaelefrn** [comment]
si

2016-02-18 21:30 GMT+01:00 Fabio Z Tessitore notifications@github.com:
