### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/Helloworld1#4]
Creare un programma hello.py che chieda il nome
dell'utente e poi stampi la stringa "Hello, yourname"

**Comment by Raffaelefrn** [comment]
Programma caricato

2016-02-16 21:43 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
sorry, bisogna stampare il nome

**Comment by Raffaelefrn** [comment]
hello e il nome di fianco ?

2016-02-22 19:19 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
Si si. Avevo fatto un errore nel testo dell'esercizio. Vedi che ho corretto

Il mercoledì 24 febbraio 2016, Raffaelefrn notifications@github.com ha
scritto:

**Comment by Raffaelefrn** [comment]
programma modificato e caricato

2016-02-24 20:54 GMT+01:00 Fabio Z Tessitore notifications@github.com:
