### ISSUE TITLE
Sfera

### ISSUE THREAD

**Issue by FabioZTessitore** [Raffaelefrn/Helloworld1#7]
Creare un programma sfera.py che chieda all'utente
il raggio di una sfera (intero) e ne stampi superficie e volume

Note:
Per portare a termine il compito e'
necessaria la costante matematica pi greco.
Si puo' definire una variabile assegnandole tale valore:

``` python
pi = 3.141592654
```

Oppure si puo' utilizzare quella gia'
definita nella libreria matematica:

``` python
import math

...

math.pi

...
```

**Comment by Raffaelefrn** [comment]
programma caricato

2016-02-17 14:30 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
cerca di usare tutte variabili float

**Comment by Raffaelefrn** [comment]
Fatto, vedete se va bene

2016-02-22 19:24 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
per curiosità mi spieghi perché al 4 hai messo due 0 dopo la virgola e al 3 nessuno?

**Comment by Raffaelefrn** [comment]
mi so scordato hhhahahahahahah scusate

2016-02-28 13:29 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
pensavo aggiustassi. troppa pigrizia?

**Comment by Raffaelefrn** [comment]
scusate, oggi mi è arrivato internet, dicevamo ??

2016-02-28 15:21 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
devi aggiustare i numeri in virgola mobile, poi passiamo oltre

**Comment by Raffaelefrn** [comment]
prof ho fatto le modifiche che avete detto

2016-03-10 22:45 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
non ce la posso fare hahaha hai messo il doppio zero???? e che è, FARINA???

**Comment by Raffaelefrn** [comment]
e allora in che senso la virgola mobile hahahhahaha

2016-03-14 15:57 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
3.0
4.0
